name: Deploy to EC2 Instance 

on:
  push: 
    branches:  
      - main
    paths: 
      - 'dags/**'  # this is our Folder name we created for Airflow
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ec2-13-60-180-73.eu-north-1.compute.amazonaws.com  # Your EC2 Host name
          username: airflow  # Your EC2 Username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Secret Variable we created
          source: dag.py  # This is our Source File name placed in Airflow-scripts Folder
          target: /home/airflow/airflow/dags/  # Your target folder in EC2 where you want to create the file